### PR TITLE
shuffle feature

### PR DESCRIPTION
**Pull request by walksanatora**
add the `--sh`/`--shuffle` option that shuffles playlist

### CODE REVIEW

**Comment by walksanatora** [comment]
next feature to add: next/previous song skipping
which i will make a setting

**Comment by Commandcracker** [comment]
_PR workflows are currently not running #66_ 
When loop_playlist is on, it will shuffle the playlist every loop.
This might be a good idea to keep, it adds moor variety if you permanently loop.
What do you think, should it be keeped ?

**Comment by Commandcracker** [comment]
Ill look at this tomorow, its quite late for me.

**Comment by walksanatora** [comment]
i am impartial either way
if you want i could add `--so` and `--shuffle-once` that shuffles once instead of every iteration

**Pull request merged**
