### PR TITLE
Skip/Back buttons for more media player functionality

### PR DESCRIPTION
**Pull request by walksanatora**
defaults to a/d for back/skip 
also adds a setting to set max buffer size

### CODE REVIEW

**Comment by walksanatora** [comment]
Merge time :>

**Comment by Commandcracker** [comment]
Screenshot_20221221_195639

**Comment by walksanatora** [comment]
I think you tried to go back before there were any songs played correct

**Comment by walksanatora** [comment]
time to add a nil check

**Comment by walksanatora** [comment]
fixed @Commandcracker this should fix your problem

**Comment by walksanatora** [comment]
now it is pull time

**Comment by Commandcracker** [comment]
Screenshot_20221221_204343

**Comment by Commandcracker** [comment]
HEY DON'T STEEL PARTS OF MY CODE !!!
Screenshot_20221221_204551

**Comment by walksanatora** [comment]
i need to change that key, because currently it works on a or the key you actually press

**Comment by walksanatora** [comment]
> HEY DON'T STEEL PARTS OF MY CODE !!! Screenshot_20221221_204551

then dont push it

**Comment by walksanatora** [comment]
also it is steal
steel is a word used for processed iron that is very usefull in construction

**Comment by Commandcracker** [comment]
AHHHHHHHHH Merge conflicts 
Screenshot_20221221_205436

**Comment by walksanatora** [comment]
just click accept incoming
since i dont see anything in your code that needs to remain/is critical/is debug

**Comment by walksanatora** [comment]
actually accept current for the second one

**Comment by walksanatora** [comment]
or just click accept both idrc

**Comment by walksanatora** [comment]
so does this mean it is finally `merge time (real)`

**Comment by Commandcracker** [comment]
Yes but I'm thinking about adding an event, when a video is skipped

**Comment by walksanatora** [comment]
i also think down the line we should tell the server if we skip
so it can dispose of the websocket instead of a sudden client disconnect
but that is probally not 100% needed

**Comment by Commandcracker** [comment]
the client is not disconnecting when a video is skipped

**Comment by Commandcracker** [comment]
The client disconnects only here 
Screenshot_20221221_210523

**Comment by walksanatora** [comment]
idk why, but i thought a new websocket was formed for every video

**Comment by Commandcracker** [comment]
No, I make efficient code :smirk:

**Comment by walksanatora** [comment]
also may i suggest the possibility of a `debug` function akin to print that prints to console is -v
and will always print to debugger peripheral (on craftos)

**Comment by Commandcracker** [comment]
i also though of it, but i was too lazy to add it :P

**Comment by walksanatora** [comment]
should i include that in this PR or make another one for that

**Comment by Commandcracker** [comment]
i would say another.
is there some word for skip back ?

**Comment by walksanatora** [comment]
press `a` it skips to previous song
currently no bind for restart song

**Comment by walksanatora** [comment]
so you could do `a` then `d` to restart

**Comment by walksanatora** [comment]
should i add another keybind for that

**Comment by Commandcracker** [comment]
yes lets just do it all in one big pr (also the debugging)

**Comment by walksanatora** [comment]
okay adding `youcube.keys.restart` defaulting to `r`
and a debug function that does the same thing as print (but only if verbose)

**Comment by walksanatora** [comment]
done
restart keybind + debug function

**Comment by walksanatora** [comment]
wait ... 
this needs to be within play ...
so you can restart any song

**Comment by walksanatora** [comment]
wait no
this does not work if play is not looping

**Comment by walksanatora** [comment]
mabey that fixed it, too lazy to fix

**Comment by Commandcracker** [comment]
Wen the CraftOS-PC debugger is open then YC will lag
-_- fix your code jack

**Comment by walksanatora** [comment]
Works on my machine
(I dont lag)
Source: i was using youcube on my laptop for the past 3 hours with the debugger open  as a mp3 player

**Comment by Commandcracker** [comment]
now im confused

**Comment by walksanatora** [comment]
when i use youcube in Craftos-pc with the debugger it does not lag
i know this because i was playing my youtube playlist on loop for the past 3 hours

**Pull request merged**
